In [215]:
import pandas as pd

In [228]:
df = pd.read_csv('D:\\Desktop\\Data Science\\python\\Messy_Employee_dataset.csv')

In [217]:
df.info
df.head(5)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [218]:
df[df.isnull().any(axis = 1)]

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
6,EMP1006,Frank,Jones,NaN,Admin-Nevada,Active,4/3/2020,96288.43,frank.jones@example.com,-4518376063,Good,False
9,EMP1009,Charlie,Johnson,NaN,DevOps-New York,Active,8/4/2022,76561.88,charlie.johnson@example.com,-8156985699,Excellent,True
11,EMP1011,David,Davis,NaN,DevOps-California,Active,9/4/2023,84946.19,david.davis@example.com,-1238296576,Poor,True
...,...,...,...,...,...,...,...,...,...,...,...,...
1006,EMP2006,Grace,Brown,NaN,HR-Illinois,Inactive,10/25/2023,77821.79,grace.brown@example.com,-119236036,Average,False
1009,EMP2009,David,Garcia,NaN,Finance-Illinois,Pending,6/11/2024,62603.98,david.garcia@example.com,-7315391148,Poor,False
1012,EMP2012,Grace,Miller,35.0,DevOps-Florida,Inactive,4/15/2023,NaN,grace.miller@example.com,-6557820189,Average,False
1013,EMP2013,Eva,Williams,NaN,HR-Illinois,Pending,2/6/2020,116680.63,eva.williams@example.com,-4322302332,Good,False
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True

# Issues in the data were determined, let's solve them one by one :)

## >>>>> Missing data in the age column

In [219]:
# I didn't just want to fill the missing values with the general mean but has taken the mean of each department region

total_mean= df["Age"].mean()
df["Age"] = df["Age"].fillna( df.groupby("Department_Region")["Age"].transform("mean").astype(int)).fillna(total_mean)
df.head(5)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,34.0,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,32.0,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False


## >>>>> Missing data in the salary column

In [220]:
total_mean= df["Salary"].mean()
df["Salary"] = df["Salary"].fillna( df.groupby("Department_Region")["Salary"].transform("mean").astype(int)).fillna(total_mean)
df.head(5)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,34.0,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,32.0,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

## >>>>> incorrect symbol in the number column

In [221]:
df["Phone"] = df["Phone"].astype(str).str.replace("-", "")
df.head(3)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,34.0,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,32.0,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,5596363211,Good,True

# Let's now do a small test

In [222]:
df[df.isnull().any(axis = 1)]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Department_Region, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work]
Index: []

# Yaay, Now the data is clean and ready for some analysis!

In [223]:
df[["Age", "Salary"]].corr()

            Age   Salary
Age     1.00000  0.07741
Salary  0.07741  1.00000